dist: xenial
language: python
python:
  - 3.7
sudo: true
install:
  - pip install PrettyTable
script:
  - cd foo
  - python -m unittest tests.TestGED_us01
  - python -m unittest tests.TestGED_us02
  - python -m unittest tests.TestGED_us03_us04
  - python -m unittest tests.TestGED_us05
  - python -m unittest tests.TestGED_us06
  - python -m unittest tests.TestGED_us07
  - python -m unittest tests.TestGED_us10
  - python -m unittest tests.TestGED_us12
  - python -m unittest test_report
